var IndigoBookTables = {
  // T11. Required Abbreviations for Case Names in Citations, Periodical Titles, and Institutional Authors (Common Words)
  table11: {
    "Academic": "Acad.",
    "Academy": "Acad.",
    "Accountant": "Acct.",
    "Accounting": "Acct.",
    "Accountancy": "Acct.",
    "Administrative": "Admin.",
    "Administration": "Admin.",
    "Administrator": "Adm'r, Adm'x",
    "Administratrix": "Adm'r, Adm'x",
    "Advertising": "Advert.",
    "Advocate": "Advoc.",
    "Advocacy": "Advoc.",
    "Affair": "Aff.",
    "Africa": "Afr.",
    "African": "Afr.",
    "Agriculture": "Agric.",
    "Agricultural": "Agric.",
    "Alliance": "All.",
    "Alternative": "Alt.",
    "Amendment": "Amend.",
    "America": "Am.",
    "American": "Am.",
    "and": "&",
    "Annual": "Ann.",
    "Appellate": "App.",
    "Arbitration": "Arb.",
    "Arbitrator": "Arb.",
    "Artificial Intelligence": "A.I.",
    "Associate": "Assoc.",
    "Association": "Ass'n",
    "Atlantic": "Atl.",
    "Attorney": "Att'y",
    "Authority": "Auth.",
    "Automobile": "Auto.",
    "Automotive": "Auto.",
    "Avenue": "Ave.",
    "Bankruptcy": "Bankr.",
    "Behavior": "Behav.",
    "Behavioral": "Behav.",
    "Board": "Bd.",
    "Broadcaster": "Broad.",
    "Broadcasting": "Broad.",
    "Brotherhood": "Bhd.",
    "Brothers": "Bros.",
    "Building": "Bldg.",
    "Business": "Bus.",
    "Businesses": "Bus.",
    "Capital": "Cap.",
    "Casualty": "Cas.",
    "Casualties": "Cas.",
    "Catholic": "Cath.",
    "Center": "Ctr.",
    "Centre": "Ctr.",
    "Central": "Cent.",
    "Chemical": "Chem.",
    "Children": "Child.",
    "Chronicle": "Chron.",
    "Circuit": "Cir.",
    "Coalition": "Coal.",
    "College": "Coll.",
    "Commentary": "Comment.",
    "Commission": "Comm'n",
    "Commissioner": "Comm'r",
    "Committee": "Comm.",
    "Communication": "Commc'n",
    "Communications": "Commc'ns",
    "Community": "Cmty.",
    "Company": "Co.",
    "Comparative": "Compar.",
    "Compensation": "Comp.",
    "Computer": "Comput.",
    "Computing": "Comput.",
    "Computational": "Comput.",
    "Condominium": "Condo.",
    "Conference": "Conf.",
    "Congress": "Cong.",
    "Congressional": "Cong.",
    "Consolidated": "Consol.",
    "Construction": "Constr.",
    "Contemporary": "Contemp.",
    "Continental": "Cont'l",
    "Contract": "Cont.",
    "Conveyance": "Conv.",
    "Conveyancer": "Conv.",
    "Cooperation": "Coop.",
    "Cooperative": "Coop.",
    "Corporate": "Corp.",
    "Corporation": "Corp.",
    "Corrections": "Corr.",
    "Correctional": "Corr.",
    "Cosmetic": "Cosm.",
    "Counselor": "Couns.",
    "Counselors": "Couns.",
    "Counselor\u2019s": "Couns.",
    "Counseling": "Couns.",
    "County": "Cnty.",
    "Defend": "Def.",
    "Defender": "Def.",
    "Defense": "Def.",
    "Defensive": "Def.",
    "Delinquent": "Delinq.",
    "Delinquency": "Delinq.",
    "Department": "Dep't",
    "Detention": "Det.",
    "Developer": "Dev.",
    "Development": "Dev.",
    "Digest": "Dig.",
    "Digital": "Digit.",
    "Diplomacy": "Dipl.",
    "Diplomat": "Dipl.",
    "Diplomatic": "Dipl.",
    "Director": "Dir.",
    "Discount": "Disc.",
    "Dispute": "Disp.",
    "Distributor": "Distrib.",
    "Distributing": "Distrib.",
    "Distribution": "Distrib.",
    "District": "Dist.",
    "Division": "Div.",
    "Doctor": "Dr.",
    "East": "E.",
    "Eastern": "E.",
    "Economic": "Econ.",
    "Economical": "Econ.",
    "Economics": "Econ.",
    "Economy": "Econ.",
    "Editor": "Ed.",
    "Editorial": "Ed.",
    "Educate": "Educ.",
    "Education": "Educ.",
    "Educating": "Educ.",
    "Educational": "Educ.",
    "Educator": "Educ.",
    "Electric": "Elec.",
    "Electrical": "Elec.",
    "Electricity": "Elec.",
    "Electronic": "Elec.",
    "Employee": "Emp.",
    "Employer": "Emp.",
    "Employment": "Emp.",
    "Enforcement": "Enf't",
    "Engineer": "Eng'r",
    "Engineering": "Eng'g",
    "English": "Eng.",
    "Enterprise": "Enter.",
    "Entertainment": "Ent.",
    "Environment": "Env't",
    "Environmental": "Env't",
    "Equality": "Equal.",
    "Equipment": "Equip.",
    "Estate": "Est.",
    "Examiner": "Exam'r",
    "Exchange": "Exch.",
    "Executive": "Exec.",
    "Executor": "Ex'[r, x]",
    "Executrix": "Ex'[r, x]",
    "Exploration": "Expl.",
    "Exploratory": "Expl.",
    "Exporter": "Exp.",
    "Exportation": "Exp.",
    "Faculty": "Fac.",
    "Federal": "Fed.",
    "Federation": "Fed'n",
    "Fidelity": "Fid.",
    "Finance": "Fin.",
    "Financial": "Fin.",
    "Financing": "Fin.",
    "Fortnightly": "Fort.",
    "Forum": "F.",
    "Foundation": "Found.",
    "General": "Gen.",
    "Global": "Glob.",
    "Government": "Gov't",
    "Group": "Grp.",
    "Guaranty": "Guar.",
    "Guarantor": "Guar.",
    "Hispanic": "Hisp.",
    "Historical": "Hist.",
    "History": "Hist.",
    "Hospital": "Hosp.",
    "Hospitality": "Hosp.",
    "Housing": "Hous.",
    "Human": "Hum.",
    "Import": "Imp.",
    "Importer": "Imp.",
    "Importation": "Imp.",
    "Incorporated": "Inc.",
    "Indemnity": "Indem.",
    "Independence": "Indep.",
    "Independent": "Indep.",
    "Industry": "Indus.",
    "Industries": "Indus.",
    "Industrial": "Indus.",
    "Inequality": "Ineq.",
    "Information": "Info.",
    "Institute": "Inst.",
    "Institution": "Inst.",
    "Insurance": "Ins.",
    "Intellectual": "Intell.",
    "Intelligence": "Intel.",
    "Interdisciplinary": "Interdisc.",
    "Interest": "Int.",
    "International": "Int'l",
    "Investment": "Inv.",
    "Investor": "Inv.",
    "Journal": "J.",
    "Journals": "J.",
    "Judicial": "Jud.",
    "Juridicial": "Jurid.",
    "Jurisprudence": "Juris.",
    "Justice": "Just.",
    "Juvenile": "Juv.",
    "Labor": "Lab.",
    "Laboratory": "Lab'y",
    "Law": "L.",
    "Lawyer": "Law.",
    "Legislate": "Legis.",
    "Legislation": "Legis.",
    "Legislative": "Legis.",
    "Liability": "Liab.",
    "Library": "Libr.",
    "Librarian": "Libr.",
    "Limited": "Ltd.",
    "Litigation": "Litig.",
    "Local": "Loc.",
    "Machine": "Mach.",
    "Machinery": "Mach.",
    "Magazine": "Mag.",
    "Maintenance": "Maint.",
    "Management": "Mgmt.",
    "Manufacturer": "Mfr.",
    "Manufacturing": "Mfg.",
    "Maritime": "Mar.",
    "Market": "Mkt.",
    "Marketing": "Mktg.",
    "Matrimonial": "Matrim.",
    "Mechanic": "Mech.",
    "Mechanical": "Mech.",
    "Medical": "Med.",
    "Medicinal": "Med.",
    "Medicine": "Med.",
    "Memorial": "Mem'l",
    "Merchant": "Merch.",
    "Merchandise": "Merch.",
    "Merchandising": "Merch.",
    "Metropolitan": "Metro.",
    "Military": "Mil.",
    "Mineral": "Min.",
    "Modern": "Mod.",
    "Mortgage": "Mortg.",
    "Municipal": "Mun.",
    "Municipality": "Mun.",
    "Mutual": "Mut.",
    "National": "Nat'l",
    "Nationality": "Nat'y",
    "Natural": "Nat.",
    "Negligence": "Negl.",
    "Negotiation": "Negot.",
    "Negotiator": "Negot.",
    "Newsletter": "Newsl.",
    "North": "N.",
    "Northern": "N.",
    "Northeast": "Ne.",
    "Northeastern": "Ne.",
    "Northwest": "Nw.",
    "Northwestern": "Nw.",
    "Number": "No.",
    "Office": "Off.",
    "Official": "Off.",
    "Opinion": "Op.",
    "Order": "Ord.",
    "Organization": "Org.",
    "Organizing": "Org.",
    "Pacific": "Pac.",
    "Parish": "Par.",
    "Partnership": "P'ship",
    "Patent": "Pat.",
    "Person": "Pers.",
    "Personal": "Pers.",
    "Personnel": "Pers.",
    "Perspective": "Persp.",
    "Pharmaceutic": "Pharm.",
    "Pharmaceutical": "Pharm.",
    "Philosophical": "Phil.",
    "Philosophy": "Phil.",
    "Planning": "Plan.",
    "Policy": "Pol'y",
    "Politic": "Pol.",
    "Political": "Pol.",
    "Politics": "Pol.",
    "Practical": "Prac.",
    "Practice": "Prac.",
    "Practitioner": "Prac.",
    "Preserve": "Pres.",
    "Preservation": "Pres.",
    "Privacy": "Priv.",
    "Private": "Priv.",
    "Probate": "Prob.",
    "Probation": "Prob.",
    "Problems": "Probs.",
    "Proceedings": "Proc.",
    "Procedure": "Proc.",
    "Product": "Prod.",
    "Production": "Prod.",
    "Profession": "Pro.",
    "Professional": "Pro.",
    "Property": "Prop.",
    "Protection": "Prot.",
    "Psychological": "Psych.",
    "Psychologist": "Psych.",
    "Psychology": "Psych.",
    "Public": "Pub.",
    "Publication": "Publ'n",
    "Publishing": "Publ'g",
    "Quarterly": "Q.",
    "Railroad": "R.R.",
    "Railway": "Ry.",
    "Record": "Rec.",
    "Referee": "Ref.",
    "Refining": "Refin.",
    "Refinement": "Refin.",
    "Regional": "Reg'l",
    "Register": "Reg.",
    "Regulation": "Regul.",
    "Regulator": "Regul.",
    "Regulatory": "Regul.",
    "Rehabilitation": "Rehab.",
    "Rehabilitative": "Rehab.",
    "Relation": "Rel.",
    "Report": "Rep.",
    "Reporter": "Rep.",
    "Reproduction": "Reprod.",
    "Reproductive": "Reprod.",
    "Research": "Rsch.",
    "Reservation": "Rsrv.",
    "Reserve": "Rsrv.",
    "Resolution": "Resol.",
    "Resource": "Res.",
    "Resources": "Res.",
    "Responsibility": "Resp.",
    "Restaurant": "Rest.",
    "Retirement": "Ret.",
    "Review": "Rev.",
    "Revista": "Rev.",
    "Rights": "Rts.",
    "Road": "Rd.",
    "Savings": "Sav.",
    "School": "Sch.",
    "Science": "Sci.",
    "Scientific": "Sci.",
    "Scottish": "Scot.",
    "Secretary": "Sec'y",
    "Security": "Sec.",
    "Securities": "Sec.",
    "Sentencing": "Sent'g",
    "Service": "Serv.",
    "Shareholder": "S'holder",
    "Stockholder": "S'holder",
    "Social": "Soc.",
    "Society": "Soc'y",
    "Sociological": "Socio.",
    "Sociology": "Socio.",
    "Solicitor": "Solic.",
    "Solution": "Sol.",
    "South": "S.",
    "Southern": "S.",
    "Southeast": "Se.",
    "Southeastern": "Se.",
    "Southwest": "Sw.",
    "Southwestern": "Sw.",
    "Statistic": "Stat.",
    "Statistics": "Stat.",
    "Statistical": "Stat.",
    "Steamship": "S.S.",
    "Steamships": "S.S.",
    "Street": "St.",
    "Studies": "Stud.",
    "Subcommittee": "Subcomm.",
    "Supreme Court": "Sup. Ct.",
    "Surety": "Sur.",
    "System": "Sys.",
    "Systems": "Sys.",
    "Taxation": "Tax'n",
    "Teacher": "Tchr.",
    "Technical": "Tech.",
    "Technique": "Tech.",
    "Technological": "Tech.",
    "Technology": "Tech.",
    "Telecommunication": "Telecomm.",
    "Telephone": "Tel.",
    "Telegraph": "Tel.",
    "Temporary": "Temp.",
    "Township": "Twp.",
    "Transcontinental": "Transcon.",
    "Transnational": "Transnat'l",
    "Transport": "Transp.",
    "Transportation": "Transp.",
    "Tribune": "Trib.",
    "Trust": "Tr.",
    "Trustee": "Tr.",
    "Turnpike": "Tpk.",
    "Uniform": "Unif.",
    "United States": "U.S.",
    "University": "U.",
    "Urban": "Urb.",
    "Utility": "Util.",
    "Village": "Vill.",
    "Week": "Wk.",
    "Weekly": "Wkly.",
    "West": "W.",
    "Western": "W.",
    "Yearbook": "Y.B.",
    "Year Book": "Y.B."
  },
  // T12. Required Abbreviations for Geographical Terms
  table12: {
    "Alabama": "Ala.",
    "Alaska": "Alaska",
    "Arizona": "Ariz.",
    "Arkansas": "Ark.",
    "California": "Cal.",
    "Colorado": "Colo.",
    "Connecticut": "Conn.",
    "Delaware": "Del.",
    "Florida": "Fla.",
    "Georgia": "Ga.",
    "Hawaii": "Haw.",
    "Idaho": "Idaho",
    "Illinois": "Ill.",
    "Indiana": "Ind.",
    "Iowa": "Iowa",
    "Kansas": "Kan.",
    "Kentucky": "Ky.",
    "Louisiana": "La.",
    "Maine": "Me.",
    "Maryland": "Md.",
    "Massachusetts": "Mass.",
    "Michigan": "Mich.",
    "Minnesota": "Minn.",
    "Mississippi": "Miss.",
    "Missouri": "Mo.",
    "Montana": "Mont.",
    "Nebraska": "Neb.",
    "Nevada": "Nev.",
    "New Hampshire": "N.H.",
    "New Jersey": "N.J.",
    "New Mexico": "N.M.",
    "New York": "N.Y.",
    "North Carolina": "N.C.",
    "North Dakota": "N.D.",
    "Ohio": "Ohio",
    "Oklahoma": "Okla.",
    "Oregon": "Or.",
    "Pennsylvania": "Pa.",
    "Rhode Island": "R.I.",
    "South Carolina": "S.C.",
    "South Dakota": "S.D.",
    "Tennessee": "Tenn.",
    "Texas": "Tex.",
    "Utah": "Utah",
    "Vermont": "Vt.",
    "Virginia": "Va.",
    "Washington": "Wash.",
    "West Virginia": "W. Va.",
    "Wisconsin": "Wis.",
    "Wyoming": "Wyo.",
    "Baltimore": "Balt.",
    "Boston": "Bos.",
    "Chicago": "Chi.",
    "Dallas": "Dall.",
    "District of Columbia": "D.C.",
    "Houston": "Hous.",
    "Los Angeles": "L.A.",
    "Miami": "Mia.",
    "New York": "N.Y.C.",
    "Philadelphia": "Phila.",
    "Phoenix": "Phx.",
    "San Francisco": "S.F.",
    "American Samoa": "Am. Sam.",
    "Guam": "Guam",
    "Northern Mariana Islands": "N. Mar. I.",
    "Puerto Rico": "P.R.",
    "Virgin Islands": "V.I.",
    "Australian Capital Territory": "Austl. Cap. Terr.",
    "New South Wales": "N.S.W.",
    "Northern Territory": "N. Terr.",
    "Queensland": "Queensl.",
    "South Australia": "S. Austl.",
    "Tasmania": "Tas.",
    "Victoria": "Vict.",
    "Western Australia": "W. Austl.",
    "Alberta": "Alta.",
    "British Columbia": "B.C.",
    "Manitoba": "Man.",
    "New Brunswick": "N.B.",
    "Newfoundland & Labrador": "Nfld.",
    "Northwest Territories": "N.W.T.",
    "Nova Scotia": "N.S.",
    "Nunavut": "Nun.",
    "Ontario": "Ont.",
    "Prince Edward Island": "P.E.I.",
    "Quebec": "Que.",
    "Saskatchewan": "Sask.",
    "Yukon": "Yukon",
    "Afghanistan": "Afg.",
    "Africa": "Afr.",
    "Albania": "Alb.",
    "Algeria": "Alg.",
    "Andorra": "Andorra",
    "Angola": "Angl.",
    "Anguilla": "Anguilla",
    "Antarctica": "Antarctica",
    "Antigua & Barbuda": "Ant. & Barb.",
    "Argentina": "Arg.",
    "Armenia": "Arm.",
    "Asia": "Asia",
    "Australia": "Austl.",
    "Austria": "Austria",
    "Azerbaijan": "Azer.",
    "Bahamas": "Bah.",
    "Bahrain": "Bahr.",
    "Bangladesh": "Bangl.",
    "Barbados": "Barb.",
    "Belarus": "Belr.",
    "Belgium": "Belg.",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bermuda": "Berm.",
    "Bhutan": "Bhutan",
    "Bolivia": "Bol.",
    "Bosnia and Herzegovina": "Bosn. & Herz.",
    "Botswana": "Bots.",
    "Brazil": "Braz.",
    "Brunei": "Brunei",
    "Bulgaria": "Bulg.",
    "Burkina Faso": "Burk. Faso",
    "Burundi": "Burundi",
    "Cambodia": "Cambodia",
    "Cameroon": "Cameroon",
    "Canada": "Can.",
    "Cape Verde": "Cape Verde",
    "Cayman Islands": "Cayman Is.",
    "Central African Republic": "Cent. Afr. Rep.",
    "Chad": "Chad",
    "Chile": "Chile",
    "China, People’s Republic of": "China",
    "Colombia": "Colom.",
    "Comoros": "Comoros",
    "Congo, Democratic Republic of the": "Dem. Rep. Congo",
    "Congo, Republic of the": "Congo",
    "Costa Rica": "Costa Rica",
    "Côte d'Ivoire": "Côte d'Ivoire",
    "Croatia": "Croat.",
    "Cuba": "Cuba",
    "Cyprus": "Cyprus",
    "Czech Republic": "Czech",
    "Denmark": "Den.",
    "Djibouti": "Djib.",
    "Dominica": "Dominica",
    "Dominican Republic": "Dom. Rep.",
    "Ecuador": "Ecuador",
    "Egypt": "Egypt",
    "El Salvador": "El Sal.",
    "England": "Eng.",
    "Equatorial Guinea": "Eq. Guinea",
    "Eritrea": "Eri.",
    "Estonia": "Est.",
    "Ethiopia": "Eth.",
    "Europe": "Eur.",
    "Falkland Islands": "Falkland Is.",
    "Fiji": "Fiji",
    "Finland": "Fin.",
    "France": "Fr.",
    "Gabon": "Gabon",
    "Gambia": "Gam.",
    "Georgia": "Geor.",
    "Germany": "Ger.",
    "Ghana": "Ghana",
    "Gibraltar": "Gib.",
    "Great Britain": "Gr. Brit.",
    "Greece": "Greece",
    "Greenland": "Green.",
    "Grenada": "Gren.",
    "Guadeloupe": "Guad.",
    "Guatemala": "Guat.",
    "Guinea": "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    "Guyana": "Guy.",
    "Haiti": "Haiti",
    "Honduras": "Hond.",
    "Hong Kong": "H.K.",
    "Hungary": "Hung.",
    "Iceland": "Ice.",
    "India": "India",
    "Indonesia": "Indon.",
    "Iran": "Iran",
    "Iraq": "Iraq",
    "Ireland": "Ir.",
    "Israel": "Isr.",
    "Italy": "It.",
    "Jamaica": "Jam.",
    "Japan": "Japan",
    "Jordan": "Jordan",
    "Kazakhstan": "Kaz.",
    "Kenya": "Kenya",
    "Kiribati": "Kiribati",
    "Korea, North": "N. Kor.",
    "Korea, South": "S. Kor.",
    "Kosovo": "Kos.",
    "Kuwait": "Kuwait",
    "Kyrgyzstan": "Kyrg.",
    "Laos": "Laos",
    "Latvia": "Lat.",
    "Lebanon": "Leb.",
    "Lesotho": "Lesotho",
    "Liberia": "Liber.",
    "Libya": "Libya",
    "Liechtenstein": "Liech.",
    "Lithuania": "Lith.",
    "Luxembourg": "Lux.",
    "Macau": "Mac.",
    "Macedonia": "Maced.",
    "Madagascar": "Madag.",
    "Malawi": "Malawi",
    "Malaysia": "Malay.",
    "Maldives": "Maldives",
    "Mali": "Mali",
    "Malta": "Malta",
    "Marshall Islands": "Marsh. Is.",
    "Martinique": "Mart.",
    "Mauritania": "Mauritania",
    "Mauritius": "Mauritius",
    "Mexico": "Mex.",
    "Micronesia": "Micr.",
    "Moldova": "Mold.",
    "Monaco": "Monaco",
    "Mongolia": "Mong.",
    "Montenegro": "Montenegro",
    "Montserrat": "Montserrat",
    "Morocco": "Morocco",
    "Mozambique": "Mozam.",
    "Myanmar": "Myan.",
    "Namibia": "Namib.",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Netherlands": "Neth.",
    "New Zealand": "N.Z.",
    "Nicaragua": "Nicar.",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "North America": "N. Am.",
    "Northern Ireland": "N. Ir.",
    "Norway": "Nor.",
    "Oman": "Oman",
    "Pakistan": "Pak.",
    "Palau": "Palau",
    "Panama": "Pan.",
    "Papua New Guinea": "Papua N.G.",
    "Paraguay": "Para.",
    "Peru": "Peru",
    "Philippines": "Phil.",
    "Pitcairn Island": "Pitcairn Is.",
    "Poland": "Pol.",
    "Portugal": "Port.",
    "Qatar": "Qatar",
    "Réunion": "Réunion",
    "Romania": "Rom.",
    "Russia": "Russ.",
    "Rwanda": "Rwanda",
    "Saint Helena": "St. Helena",
    "Saint Kitts & Nevis": "St. Kitts & Nevis",
    "Saint Lucia": "St. Lucia",
    "Saint Vincent & the Grenadines": "St. Vincent",
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "São Tomé & Príncipe": "São Tomé & Príncipe",
    "Saudi Arabia": "Saudi Arabia",
    "Scotland": "Scot.",
    "Senegal": "Sen.",
    "Serbia": "Serb.",
    "Seychelles": "Sey.",
    "Sierra Leone": "Sierra Leone",
    "Singapore": "Sing.",
    "Slovakia": "Slovk.",
    "Slovenia": "Slovn.",
    "Solomon Islands": "Solom. Is.",
    "Somalia": "Som.",
    "South Africa": "S. Afr.",
    "South America": "S. Am.",
    "Spain": "Spain",
    "Sri Lanka": "Sri Lanka",
    "Sudan": "Sudan",
    "Suriname": "Surin.",
    "Swaziland": "Swaz.",
    "Sweden": "Swed.",
    "Switzerland": "Switz.",
    "Syria": "Syria",
    "Taiwan": "Taiwan",
    "Tajikistan": "Taj.",
    "Tanzania": "Tanz.",
    "Thailand": "Thai.",
    "Timor-Leste (East Timor)": "Timor-Leste",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad & Tobago": "Trin. & Tobago",
    "Tunisia": "Tunis.",
    "Turkey": "Turk.",
    "Turkmenistan": "Turkm.",
    "Turks & Caicos Islands": "Turks & Caicos Is.",
    "Tuvalu": "Tuvalu",
    "Uganda": "Uganda",
    "Ukraine": "Ukr.",
    "United Arab Emirates": "U.A.E.",
    "United Kingdom": "U.K.",
    "United States of America": "U.S.",
    "Uruguay": "Uru.",
    "Uzbekistan": "Uzb.",
    "Vanuatu": "Vanuatu",
    "Vatican City": "Vatican",
    "Venezuela": "Venez.",
    "Vietnam": "Viet.",
    "Virgin Islands, British": "Virgin Is.",
    "Wales": "Wales",
    "Yemen": "Yemen",
    "Zambia": "Zam.",
    "Zimbabwe": "Zim."
  },
  // T15. Required Abbreviations for Institutional Names in Periodical Titles
  /*
  These abbreviations are required, but may be replaced by a periodical’s own preferred abbreviated title.
  Related tables are Table T11 with common words and Table T12 with geographical abbreviations.
  */  
  table15: {
    "Adelaide": "Adel.",
    "Air Force": "A.F.",
    "Albany": "Alb.",
    "American Bar Association (ABA)": "A.B.A.",
    "American Intellectual Property Law Association": "AIPLA",
    "American Law Institute": "A.L.I.",
    "American Medical Association": "AMA",
    "American Society of Composers, Authors, & Publishers": "ASCAP",
    "American University": "Am. U.",
    "Boston College": "B.C.",
    "Boston University": "B.U.",
    "Brigham Young University": "BYU",
    "Brooklyn": "Brook.",
    "Buffalo": "Buff.",
    "California (California Law Review only)": "Calif.",
    "Capital": "Cap.",
    "Chapman": "Chap.",
    "Chartered Life Underwriters": "C.L.U.",
    "Cincinnati": "Cin.",
    "City University of New York": "CUNY",
    "Cleveland": "Clev.",
    "Columbia": "Colum.",
    "Cumberland": "Cumb.",
    "Denver": "Denv.",
    "Detroit": "Det.",
    "Dickinson": "Dick.",
    "Duquesne": "Duq.",
    "East, Eastern": "E.",
    "Foreign Broadcast Information Service": "F.B.I.S.",
    "George Mason": "Geo. Mason",
    "George Washington": "Geo. Wash.",
    "Georgetown": "Geo.",
    "Gonzaga": "Gonz.",
    "Harvard": "Harv.",
    "Howard": "How.",
    "John Marshall": "J. Marshall",
    "Journal of the American Medical Association": "JAMA",
    "Judge Advocate General": "JAG",
    "Judge Advocate General's": "JAG",
    "Las Vegas": "L.V.",
    "Lawyer's Reports Annotated": "L.R.A.",
    "Loyola": "Loy.",
    "Marquette": "Marq.",
    "Melbourne": "Melb.",
    "Memphis": "Mem.",
    "New England": "New Eng.",
    "New York University": "N.Y.U.",
    "New York University School of Law": "N.Y.U.",
    "North": "N.",
    "Northern": "N.",
    "Northeast, Northeastern": "Ne.",
    "Northwest, Northwestern": "Nw.",
    "Pepperdine": "Pepp.",
    "Pittsburgh": "Pitt.",
    "Richmond": "Rich.",
    "Rocky Mountain Mineral Law Institute": "Rocky Mtn. Min. L. Inst.",
    "Saint Louis": "St. Louis",
    "San Fernando Valley": "San Fern. V.",
    "Southeast, Southeastern": "Se.",
    "South": "S.",
    "Southern": "S.",
    "Southern Methodist University": "SMU",
    "Southwest, Southwestern": "Sw.",
    "Stanford": "Stan.",
    "Temple": "Temp.",
    "Thomas Jefferson": "T. Jefferson",
    "Thomas M. Cooley": "T.M. Cooley",
    "Thurgood Marshall": "T. Marshall",
    "Toledo": "Tol.",
    "Tulane": "Tul.",
    "Universidad de Puerto Rico": "U. P.R.",
    "University of California": "U.C.",
    "University of California - Los Angeles": "UCLA",
    "University of Missouri Kansas City": "UMKC",
    "University of the District of Columbia, David A. Clarke School of Law": "UDC/DCSL",
    "University of West Los Angeles": "UWLA",
    "Valparaiso": "Val.",
    "Vanderbilt": "Vand.",
    "Villanova": "Vill.",
    "Washington & Lee": "Wash. & Lee",
    "West": "W.",
    "Western": "W.",
    "William & Mary": "Wm. & Mary",
    "William Mitchell": "Wm. Mitchell",
  }
}